//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeInscripcion.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursos
    {
        public int id_curso { get; set; }
        public string codigo_curso { get; set; }
        public string nombre_curso { get; set; }
        public string horario { get; set; }
        public string profesor { get; set; }
        public int estado_curso { get; set; }
        public string facultad { get; set; }
    }
}
